name: GPG context testing
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  BUILD_TYPE: "Release"
  DOCKER_IMAGE_NAME: "ghcr.io/openvisualcloud/intel-tiber-broadcast-suite/tiber-broadcast-suite"
  DOCKER_IMAGE_TAG: "${{ github.sha }}"
  DEBIAN_FRONTEND: "noninteractive"
  TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db"
  TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db"
  DOCKER_TMPDIR: "/mnt/docker/docker-tmp"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    permissions:
      contents: read
    steps:
      - name: GPG install
        run: |
          sudo apt update
          sudo apt install gpg
          gpg --batch --yes --pinentry-mode loopback --passphrase "qwerty123" --quick-gen-key mlinkiew@gmail.com default default
          gpg --yes --pinentry-mode loopback --armor --export-secret-key mlinkiew@gmail.com > a.gpg
          cat a.gpg

      - name: Dump GPG
        run: |
          export GPG_TTY=$(tty)
          gpg --armor --export-secret-key mlinkiew@gmail.com


